// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYcRTCFFUe_mneN2ohfLhIZ3dJRxM7Sks',
    appId: '1:270748566886:web:20f53e7453ce2ab69d34a7',
    messagingSenderId: '270748566886',
    projectId: 'miniprojectppb',
    authDomain: 'miniprojectppb.firebaseapp.com',
    storageBucket: 'miniprojectppb.firebasestorage.app',
    measurementId: 'G-3STBSEQDDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADSbjld_T0mW71U8bX2TXmvc5m0qEWkq0',
    appId: '1:270748566886:android:91e30de8b297f1ff9d34a7',
    messagingSenderId: '270748566886',
    projectId: 'miniprojectppb',
    storageBucket: 'miniprojectppb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPz5JnTEaRXLU6T3C5H1AurzJdXhllgK8',
    appId: '1:270748566886:ios:b70ec316801ac2f29d34a7',
    messagingSenderId: '270748566886',
    projectId: 'miniprojectppb',
    storageBucket: 'miniprojectppb.firebasestorage.app',
    iosBundleId: 'com.example.moodbite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPz5JnTEaRXLU6T3C5H1AurzJdXhllgK8',
    appId: '1:270748566886:ios:b70ec316801ac2f29d34a7',
    messagingSenderId: '270748566886',
    projectId: 'miniprojectppb',
    storageBucket: 'miniprojectppb.firebasestorage.app',
    iosBundleId: 'com.example.moodbite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYcRTCFFUe_mneN2ohfLhIZ3dJRxM7Sks',
    appId: '1:270748566886:web:19c4fee51c18962b9d34a7',
    messagingSenderId: '270748566886',
    projectId: 'miniprojectppb',
    authDomain: 'miniprojectppb.firebaseapp.com',
    storageBucket: 'miniprojectppb.firebasestorage.app',
    measurementId: 'G-MHWRDT8E56',
  );

}